volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    container_name: db
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: kittygram_backend
    container_name: backend
    build: ./backend/
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static:/app/static_backend
      - media:/app/media
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 kittygram_backend.wsgi:application"

  frontend:
    image: kittygram_frontend
    container_name: frontend
    build: ./frontend/
    env_file:
      - .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: kittygram_gateway
    container_name: gateway
    build: ./nginx/
    env_file:
      - .env
    depends_on:
      - backend
      - frontend
    ports:
      - "9000:80"
    volumes:
      - static:/static
      - media:/media