volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend/
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static:/backend_static
      - media:/app/media
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             cp -r /app/collected_static/. /backend_static/ &&
             gunicorn --bind 0.0.0.0:9000 kittygram_backend.wsgi:application"

  frontend:
    env_file:
      - .env
    build: ./frontend/
    command: cp -r /app/build/. /staticfiles/
    volumes:
      - static:/staticfiles

  gateway:
    build: ./nginx/
    env_file:
      - .env
    depends_on:
      - backend
      - frontend
    ports:
      - "9000:80"
    volumes:
      - static:/staticfiles
      - media:/media